Minecraft 1.19.3
UeberallGebannt/server-softwares pull request #22
Opened 2023-01-05 13:51 UTC by TonimatasDEV

2023-01-05 17:45 UTC, UeberallGebannt commented
Thank you for your PR! I will take are more detailed look at it later this evening ^^

2023-01-06 06:28 UTC, UeberallGebannt requested changes
I added some comments to parts of the code, please take a look at them.
Beside from some small things, it looks very good ^^

2023-01-06 06:28 UTC, UeberallGebannt commented on RECOMMEND.md
> +  - If you want to use Forge mods and plugins on **1.16.5 or 1.19.2** you can use [Mohist](https://github.com/UeberallGebannt/server-softwares/blob/master/SERVERS.md#-mohist).
Mohist doesn't actually support 1.19.2 yet.
I'd say we recommend Arclight for that version.
For 1.16.5 I'd say we recommend Mohist (as I don't know how well Arclight works for that version).

2023-01-06 06:28 UTC, UeberallGebannt commented on SERVERS.md
> +  - Version: 1.7.10-1.17.1 (Unsupported), 1.18.2-1.19.3
As 1.18.2 is listed as legacy (https://papermc.io/legacy) I think it is unsupported too.

2023-01-06 06:28 UTC, UeberallGebannt commented on SERVERS.md
> +  - Active: ❌Temporaly (Alternatice: BurritoSpigot/SportPaper)
You have two typos right there.
"Temporarily" and "Alternative"

2023-01-06 06:28 UTC, UeberallGebannt commented on SERVERS.md
> +  - Version: 1.12.2, 1.16.5, 1.19 (Experimental)
As I was unable to find a 1.16.5 dev branch, it is most likely not supported/available anymore.

2023-01-06 06:28 UTC, UeberallGebannt commented on SERVERS.md
> +  - Version: 1.8-1.19.3
![grafik](https://user-images.githubusercontent.com/50475262/210942795-32baa7c0-248b-4a42-bf87-d8fe62255f35.png)

There is no version for 1.13.X and 1.14.X

2023-01-06 06:28 UTC, UeberallGebannt commented on SERVERS.md
> +  - Version: 1.12.2, 1.15.2 (Deprecated), 1.16.5 (Unsupported), 1.18.2 (Experimental)
1.18.2 isn't experimental anymore, it's pretty stable by now.

2023-01-06 15:00 UTC, TonimatasDEV commented on SERVERS.md
> +  - Version: 1.12.2, 1.15.2 (Deprecated), 1.16.5 (Unsupported), 1.18.2 (Experimental)
I had thought about it

2023-01-06 15:02 UTC, TonimatasDEV commented on SERVERS.md
> +  - Version: 1.8-1.19.3
Done

2023-01-06 15:02 UTC, TonimatasDEV commented on SERVERS.md
> +  - Version: 1.12.2, 1.16.5, 1.19 (Experimental)
Done

2023-01-06 15:02 UTC, TonimatasDEV commented on SERVERS.md
> +  - Version: 1.7.10-1.17.1 (Unsupported), 1.18.2-1.19.3
Done

2023-01-06 15:02 UTC, TonimatasDEV commented on RECOMMEND.md
> +  - If you want to use Forge mods and plugins on **1.16.5 or 1.19.2** you can use [Mohist](https://github.com/UeberallGebannt/server-softwares/blob/master/SERVERS.md#-mohist).
Done

2023-01-06 15:52 UTC, TonimatasDEV commented
All done

2023-01-06 17:13 UTC, merged

2023-01-06 17:13 UTC, UeberallGebannt commented
Thank you for your help :)