Add all Hybrids of AnythingsMC
UeberallGebannt/server-softwares pull request #28
Opened 2023-01-13 16:45 UTC by TonimatasDEV

Add:
- Contigo
- NeptuneForge
- PFServer
- Lava
- AtomMC
- Hotpur
- Kettle

2023-01-15 19:14 UTC, UeberallGebannt requested changes
Please take a look at my requests, other than that it looks good to me :)

2023-01-15 19:14 UTC, UeberallGebannt commented on java/MODS+PLUGINS.md
> +### [♓ Contigo](https://github.com/CyberdyneCC/Thermos)
This link leads to thermos, not Contigo

2023-01-15 19:14 UTC, UeberallGebannt commented on java/MODS+PLUGINS.md
> +- **Plugins:** Bukkit, Spigot
NeptuneForge is not implementing Bukkit or Spigot, it's implementing CanaryLib which is a fork of hMod. Therefore the Fork chain should be hMod --> CanaryMod + Forge --> NeptuneForge.

2023-01-15 19:14 UTC, UeberallGebannt commented on java/MODS+PLUGINS.md
> +- **Alternative**: -
Maybe add an alternative like Magma

2023-01-15 19:14 UTC, UeberallGebannt commented on java/MODS+PLUGINS.md
> +- **Plugins:** Bukkit, Spigot, Paper
As there is no Paper code in the AtomMC repository, it shouldn't support Paper.

2023-01-15 19:14 UTC, UeberallGebannt commented on java/MODS+PLUGINS.md
> +Discontinued
Format is missing here

2023-01-15 20:25 UTC, TonimatasDEV commented
Everything fixed except TableCloth, I couldn't find information about it

2023-01-15 20:26 UTC, TonimatasDEV commented
> Please take a look at my requests, other than that it looks good to me :)

Everything fixed except TableCloth, I couldn't find information about it

2023-01-16 15:02 UTC, UeberallGebannt approved these changes

2023-01-18 10:05 UTC, merged