Add QuiltMC
UeberallGebannt/server-softwares pull request #33
Opened 2023-01-18 17:49 UTC by TonimatasDEV

Close #31

2023-01-18 18:52 UTC, UeberallGebannt requested changes

2023-01-18 18:52 UTC, UeberallGebannt commented on java/MODS.md
> +- **Fork:** FabricMC
We need to stay consistent with the fork chain, in this case it would need an arrow leading to QuiltMC

2023-01-18 19:23 UTC, TonimatasDEV commented on java/MODS.md
> +- **Fork:** FabricMC
Done

2023-01-18 19:24 UTC, TonimatasDEV commented
Fixed

2023-01-19 07:42 UTC, UeberallGebannt approved these changes

2023-01-19 07:42 UTC, merged