update goldenforge status
UeberallGebannt/server-softwares pull request #50
Opened 2023-06-14 13:17 UTC by manugame

goldenforge is no longer Inactive

2023-06-14 13:17 UTC, manugame commented
i wasn't even aware that goldenforge was in this list x)

2023-06-24 22:25 UTC, TonimatasDEV commented
Don't delete Inactive Developement, only move GoldenForge to up

2023-06-25 14:36 UTC, UeberallGebannt requested changes

2023-06-25 14:36 UTC, UeberallGebannt commented on java/MODS.md
> +- **Description:** Fork of Forge 1.19.2 which implement some Paper patches
Please move it up instead of deleting the header :)
Also, please add all covered versions, even if inactive (you can add a note).

2023-06-25 14:37 UTC, UeberallGebannt commented
@manugame Thank you for updating this list, for some reason github decided not to inform me about your PR, which is why I didn't respond earlier 😅

2023-06-30 05:59 UTC, closed without merging