Update 1.20.1, inactive and more
UeberallGebannt/server-softwares pull request #51
Opened 2023-06-24 23:45 UTC by TonimatasDEV

- Add the missing points in the descriptions.
 - Upgrade to 1.20.1.
 - Move all software that have not had any commit in the last year to Inactive.
- Correct some typos.
- Fix some RECOMMEND.md links.

2023-06-25 14:36 UTC, UeberallGebannt requested changes

2023-06-25 14:36 UTC, UeberallGebannt commented on RECOMMEND.md
> +  - If you want to use Forge mods and plugins on **1.16.5** you can use [Mohist](/java/MODS+PLUGINS.md#-mohist).
1.16.5 already exists as an entry

2023-06-25 14:36 UTC, UeberallGebannt commented on bedrock/PLUGINS.md
> +### [💨 LiteLoader BDS](https://github.com/LiteLDev/LiteLoaderBDS)
Why did you move this into inactive, it is active.
![grafik](https://github.com/UeberallGebannt/server-softwares/assets/50475262/0f4e7192-3d47-43fc-b1f6-62005298109f)

2023-06-25 14:36 UTC, UeberallGebannt commented on java/PLUGINS.md
> +### [⬛️ Topiary](https://github.com/YatopiaMC/Yatopia)
Why did you rename this?

2023-06-25 15:01 UTC, TonimatasDEV commented on bedrock/PLUGINS.md
> +### [💨 LiteLoader BDS](https://github.com/LiteLDev/LiteLoaderBDS)
My bad, is Cloudburst not LiteLoaderBDS

2023-06-25 15:02 UTC, TonimatasDEV commented on RECOMMEND.md
> +  - If you want to use Forge mods and plugins on **1.16.5** you can use [Mohist](/java/MODS+PLUGINS.md#-mohist).
Sorry, 1.20.1, already fixed.

2023-06-25 15:02 UTC, TonimatasDEV commented on java/PLUGINS.md
> +### [⬛️ Topiary](https://github.com/YatopiaMC/Yatopia)
mmm? I don't know what happened there but it's fixed now.

2023-06-29 20:25 UTC, TonimatasDEV commented
@UeberallGebannt All you request are done

2023-06-30 05:58 UTC, UeberallGebannt approved these changes
LGTM!

2023-06-30 05:59 UTC, merged