Seperate Cauldron and MCPC+
UeberallGebannt/server-softwares pull request #57
Opened 2023-08-14 23:46 UTC by wolflord212312

Seperating Cauldron And MCPC+ as MCPC+ was  MADE by MD-5 at the time, and deserves it's own category, Also added a link to download the files hosted on tor,Fixed some spelling errors and removed paper plugins from the description of magma as only 1.12.2 can run paper plugins completely.

2023-08-14 23:57 UTC, wolflord212312 commented
Added litelaoder to mods!

2023-08-15 00:00 UTC, wolflord212312 commented on java/MODS+PLUGINS.md
> +### [MCPC+](http://rk2xq6ujanjskx7o2hs5kqfljhdzycn7pfffnwjonunj6woqzpicnpqd.onion)
You Do need TOR to Download these files For DMCA/SECURITY reasons NO EXCPETIONS OTHERWISE USE INTERNET ARCHIVE

2023-08-15 02:24 UTC, wolflord212312 commented on java/MODS+PLUGINS.md
> +### [MCPC+](http://rk2xq6ujanjskx7o2hs5kqfljhdzycn7pfffnwjonunj6woqzpicnpqd.onion)
May relocate/redo the download here as you have to download the whole source code of every version which leads to 3 hour download times lol

2023-08-15 02:56 UTC, wolflord212312 commented
KSpigot
mSpigot*
pSpigot
FlamePaper
Cleanstone

I think are all the ones i just did?

2023-08-15 03:23 UTC, wolflord212312 commented on java/FOLIA.md
> +### [🌽 Foliocopia](https://github.com/R00tB33rMan/Foliocopia)
Be aware this is a joke dont advising putting in lol

2023-08-16 14:34 UTC, UeberallGebannt requested changes
Thank you very much for your contribution! I'd love to include the mentioned softwares, but there are some suggestions I have.

2023-08-16 14:34 UTC, UeberallGebannt commented on java/PLUGINS.md
> +
As I don't want to put closed source and paid softwares on this list, please remove them.

2023-08-16 14:55 UTC, wolflord212312 commented on java/FOLIA.md
> +### [🌽 Foliocopia](https://github.com/R00tB33rMan/Foliocopia)
Removed Foliocopia

2023-08-16 14:56 UTC, wolflord212312 commented on java/PLUGINS.md
> +### [🔥 FlamePaper](https://builtbybit.com/resources/flamepaper-fix-performance-security.19660/)
Fixed

2023-08-16 14:56 UTC, wolflord212312 commented on java/PLUGINS.md
> +- **Plugins:** Bukkit, Spigot, Paper
Removed

2023-08-16 15:17 UTC, UeberallGebannt approved these changes
LGTM! Thanks for your contribution!

2023-08-16 15:19 UTC, merged